### ISSUE TITLE
v8flags node error in gulp@3.8.10

### ISSUE THREAD

**Issue by derberg** [gulpjs/gulp#810]
This is what I have in my project:

```
  "devDependencies": {
    "del": "^1.1.0",
    "gulp": "^3.8.10",
    "gulp-concat": "^2.4.2",
    "gulp-minify-css": "^0.3.11",
    "gulp-minify-html": "^0.1.7",
    "gulp-uglify": "^1.0.2"
  },
```

I have the following file available: node_modules/gulp/node_modules/v8flags/3.14.5.9.flags.json

On Mac all works but when I run the same on: Linux Debian 3.14.12-1 I get the following error:

Error: Cannot find module '/devportal/devportal/node_modules/gulp/node_modules/v8flags/3.14.5.8.flags.json'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/home/bamboouser/agent/agent-home/xml-data/build-dir/PAAS-DEVPDEV-JOB1/devportal/devportal/node_modules/gulp/bin/gulp.js:25:22)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)

which is pretty strange as I have 3.14.5.9.flags.json and he wants 3.14.5.8.flags.json
debugging didn't show anything else

**Comment by leny** [comment]
Got this error with node `0.12.0` & gulp `3.8.10` : 

    Error: Cannot find module '/usr/local/lib/node_modules/gulp/node_modules/v8flags/cache/3.28.73.flags.json'

**Comment by julianbenner** [comment]
Can confirm (Node 0.12.0, Gulp 3.8.10). Bug should be reopened.

**Comment by loris** [comment]
Same issue with node `0.12.0` and gulp `3.8.10`

**Comment by leny** [comment]
No need: the solution depicted on issue #893 works fine.

**Comment by phated** [comment]
We've fixed this and published at 3.8.11 and it works on node 0.12 from our initial testing.

**Comment by sethlivingston** [comment]
Getting the same error as @leny on `0.12` and `3.8.11`.

**Comment by sethlivingston** [comment]
(Windows) Encountered this problem when installing node 0.12 over a previous version without first uninstalling. Fixed it by uninstalling and then installing node. The old node had gulp 3.8.10 and wouldn't let go of it.

**Comment by tunix** [comment]
I'm having this issue with node 0.12 and gulp 3.8.11

```
$ gulp dev-live
module.js:338
    throw err;
          ^
Error: Cannot find module '/usr/local/lib/node_modules/gulp/node_modules/v8flags/cache/3.28.73.flags.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:25:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by kevva** [comment]
Try reinstalling gulp.

**Comment by tunix** [comment]
Already did that. Doesn't fix anything.

**Comment by tunix** [comment]
Nevermind. I had a previously installed global version but I've recently changed npm prefix to my home folder (in order to install global packages locally). Deleted the globally installed version in /usr/local/lib/node_modules , deleted $HOME/.npm folder and reinstalled. It now works.

**Comment by gregorypratt** [comment]
`npm uninstall gulp`
`npm install gulp -g`
`npm install` < local build

Seemed to sort it for me

**Comment by timbru31** [comment]
@gregorypratt +1
That worked for me (node v0.12.0 and gulp v3.8.11)

**Comment by chevdor** [comment]
Same issue, solution above worked :ok_hand: 
This is due to a global version of gulp not matching the local one and/or too old.
I already had gulp 3.8.11 locally, I ran the following.
```npm install gulp -g```
and the issue was gone.

**Comment by killswitch** [comment]
I tried uninstalling and reinstalling and I still get it. I use `nvm` to manage my node versions.

**Node:** v0.12.0
**Gulp:** 3.8.11

```
module.js:338
    throw err;
          ^
Error: Cannot find module '/usr/local/lib/node_modules/gulp/node_modules/v8flags/3.28.73.flags.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:25:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by phated** [comment]
This is no longer a bug.  Your global or local version of gulp is out of date.  Remember that gulp is installed in 2 places.

**Comment by killswitch** [comment]
I've updated both to 3.8.11 and still get it.

**Comment by killswitch** [comment]
Edit, nevermind I found the issue, I had a stray global install still in my old node install, so when I ran it, it would match `/usr/local/bin/gulp` over `~/.nvm/versions/node/v0.12.0/bin/gulp`

**Comment by SanjayKarki** [comment]
@gregorypratt 
Thanks. It worked.

**Comment by michalradziwon** [comment]
@gregorypratt :+1:  works like a charm. Thanks!

**Comment by amitrahav** [comment]
didnt work for me.
gulp 3.8.11
npm 2.5.1

not using nvm and gulp only installed once on my machine.
tried to reinstall globaly and localy but it dosent seems to work:

 ```
Error: Cannot find module '/usr/lib/node_modules/gulp/node_modules/v8flags/3.28.73.flags.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/gulp/bin/gulp.js:25:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
 ```

**Comment by cazala** [comment]
same here, i get the same error
node v0.12.0
npm 2.6.1
gulp 3.8.11

**Comment by Treverix** [comment]
Thanks, @gregorypratt, your solution worked for me! The issue popped up after upgrading to node 0.12 (mac os, homebrew)

**Comment by sapjax** [comment]
https://github.com/gulpjs/gulp/issues/873
this works
